### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by sagswe** [aGuyNamedJonas/slim-redux-react#12]
I was trying to build 0.2 branch with npm run build. I am not getting full build. How to get the working version of 0.2 build.

**Comment by aGuyNamedJonas** [comment]
Hey @sagswe, to be honest: 0.2 isn't implemented yet on the slim-redux-react side. I'm currently finishing up a few things for slim-redux (including your feature request from this issue: https://github.com/aGuyNamedJonas/slim-redux/issues/10) and only then will write the wrapper for react which is obviously this project. That's why it's probably not building atm. 

I will release beta testing information on the whole project over the weekend! I'll let you know in this issue as soon as you can start testing / messing around with it!

**Comment by aGuyNamedJonas** [comment]
Works now - YAY for BETA being finally out! 🙌🏻
